---
title: Portfolio
timezone: UTC
collections:
  poetry:
    title: Poetry
    output: true
    permalink: "/poetry/:path/"
  portfolio:
    title: Portfolio
    output: true
    permalink: "/portfolio/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: you@example.com
description: 'A simple, whitespace, helvetica based portfolio theme.

'
baseurl: 
url: 
twitter_username: twitter_username
github_username: github_username
markdown: kramdown
highlighter: pygments
paginate: 15
paginate_path: "/blog/page:num/"
